-- ===========================================================================
-- wispcord / member-bot Supabase schema
--
-- Paste this whole file into the Supabase SQL Editor and press Run.
-- Safe to run more than once: every statement is idempotent.
--
-- Access model, in one paragraph. The member page runs in a browser with the
-- **anon** key, so anything it must read has to be readable by anon — and
-- anything it must write has to be insertable by anon. It may never read a
-- ticket back out (that would leak everyone's tickets to anyone with the public
-- key), so tickets are write-only from the browser. Staff reads go through the
-- admin bot's process, which holds the service key and bypasses RLS.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. ticket_queue — new tickets submitted from the member page
-- ---------------------------------------------------------------------------
create table if not exists public.ticket_queue (
  id              bigint generated by default as identity primary key,
  ticket_id       text,
  category        text,
  subject         text,
  body            text,
  answers         jsonb default '{}'::jsonb,
  attachments     jsonb default '[]'::jsonb,
  discord_user_id text,
  discord_tag     text,
  anonymous       boolean default false,
  status          text default 'queued',
  created_at      timestamptz default now(),
  processed_at    timestamptz
);

create index if not exists ticket_queue_unprocessed_idx
  on public.ticket_queue (processed_at) where processed_at is null;

alter table public.ticket_queue enable row level security;

-- The browser may only ever ADD a ticket, never read one back.
drop policy if exists "anon can insert tickets" on public.ticket_queue;
create policy "anon can insert tickets"
  on public.ticket_queue
  for insert
  to anon
  with check (true);

drop policy if exists "service full access ticket_queue" on public.ticket_queue;
create policy "service full access ticket_queue"
  on public.ticket_queue
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 2. ticket_reply_queue — member replies to an existing ticket
-- ---------------------------------------------------------------------------
create table if not exists public.ticket_reply_queue (
  id              bigint generated by default as identity primary key,
  ticket_id       text not null,
  body            text,
  attachments     jsonb default '[]'::jsonb,
  discord_user_id text,
  discord_tag     text,
  status          text default 'queued',
  created_at      timestamptz default now(),
  processed_at    timestamptz
);

create index if not exists ticket_reply_queue_unprocessed_idx
  on public.ticket_reply_queue (processed_at) where processed_at is null;

alter table public.ticket_reply_queue enable row level security;

drop policy if exists "anon can insert replies" on public.ticket_reply_queue;
create policy "anon can insert replies"
  on public.ticket_reply_queue
  for insert
  to anon
  with check (true);

drop policy if exists "service full access ticket_reply_queue" on public.ticket_reply_queue;
create policy "service full access ticket_reply_queue"
  on public.ticket_reply_queue
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 3. bot_status — the heartbeat table. The ONLY table anon may read.
-- ---------------------------------------------------------------------------
create table if not exists public.bot_status (
  id           text primary key,
  updated_at   timestamptz default now(),
  version      text,
  guild_count  integer default 0,
  member_count integer default 0,
  latency_ms   integer default 0
);

-- Added after the first release, so an existing table needs the ALTER:
-- `create table if not exists` does nothing to a table that is already there.
-- The member bot sends uptime_seconds with every heartbeat and retries without
-- it if the column is missing, so the heartbeat still lands either way — only
-- the uptime display on the site depends on this.
alter table public.bot_status add column if not exists uptime_seconds integer default 0;

alter table public.bot_status enable row level security;

-- The member page reads the 'member' row with the anon key to decide whether
-- to paint the bot dot green. Read only: no anon insert, update or delete.
drop policy if exists "anon can read bot status" on public.bot_status;
create policy "anon can read bot status"
  on public.bot_status
  for select
  to anon
  using (true);

drop policy if exists "service full access bot_status" on public.bot_status;
create policy "service full access bot_status"
  on public.bot_status
  for all
  to service_role
  using (true)
  with check (true);

-- Seed both rows so the page has something to read before the bots boot.
insert into public.bot_status (id, version) values ('member', '0.0.0')
  on conflict (id) do nothing;
insert into public.bot_status (id, version) values ('admin', '0.0.0')
  on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 4. selfpromo_channels — server config, service key only
-- ---------------------------------------------------------------------------
create table if not exists public.selfpromo_channels (
  id         bigint generated by default as identity primary key,
  guild_id   text not null,
  channel_id text not null,
  roles      jsonb default '[]'::jsonb,
  users      jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  unique (guild_id, channel_id)
);

alter table public.selfpromo_channels enable row level security;

drop policy if exists "service full access selfpromo_channels" on public.selfpromo_channels;
create policy "service full access selfpromo_channels"
  on public.selfpromo_channels
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 5. media_only_channels — server config, service key only
-- ---------------------------------------------------------------------------
create table if not exists public.media_only_channels (
  id         bigint generated by default as identity primary key,
  guild_id   text not null,
  channel_id text not null,
  created_at timestamptz default now(),
  unique (guild_id, channel_id)
);

alter table public.media_only_channels enable row level security;

drop policy if exists "service full access media_only_channels" on public.media_only_channels;
create policy "service full access media_only_channels"
  on public.media_only_channels
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 6. pending_uploads — attachment slots awaiting their final URL
-- ---------------------------------------------------------------------------
create table if not exists public.pending_uploads (
  id           bigint generated by default as identity primary key,
  token        text unique,
  filename     text,
  content_type text,
  size_bytes   bigint,
  url          text,
  uploaded_by  text,
  status       text default 'pending',
  created_at   timestamptz default now(),
  expires_at   timestamptz default (now() + interval '1 day')
);

create index if not exists pending_uploads_token_idx on public.pending_uploads (token);

alter table public.pending_uploads enable row level security;

drop policy if exists "service full access pending_uploads" on public.pending_uploads;
create policy "service full access pending_uploads"
  on public.pending_uploads
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 7. bot_state — the member bot's own state files (economy, marriages, afk,
--    reminders, leaderboards, trivia, worker), one row per file.
--
--    This is the durable copy of the bot's JSON data: at startup the bot reads
--    any file it does not have back out of this table, and after every change
--    it refreshes the row. It is the reason a fresh host, a wiped data
--    directory or a lost disk no longer means losing balances and streaks.
--
--    Nothing on the site reads this table, and anon is deliberately given no
--    access to it — it holds private things (afk reasons, marriages, reminders)
--    and only the bot's service key should ever see them.
-- ---------------------------------------------------------------------------
create table if not exists public.bot_state (
  id         text primary key,
  data       jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table public.bot_state enable row level security;

drop policy if exists "service full access bot_state" on public.bot_state;
create policy "service full access bot_state"
  on public.bot_state
  for all
  to service_role
  using (true)
  with check (true);

-- ---------------------------------------------------------------------------
-- 8. Housekeeping — drop attachment slots older than a day.
--    Optional: only run this if `pg_cron` is available on your project.
-- ---------------------------------------------------------------------------
-- select cron.schedule(
--   'purge-pending-uploads', '0 4 * * *',
--   $$delete from public.pending_uploads where created_at < now() - interval '1 day'$$
-- );
